### ISSUE TITLE
Periods in ENS domain cause 404

### ISSUE THREAD

**Issue by auryn-macmillan** [JoinColony/colonyDapp#1798]
## Steps to reproduce

1. Create a colony with a period in the ENS domain
![SharedScreenshot](https://user-images.githubusercontent.com/8453294/64183830-7c468e80-ce38-11e9-88ba-7577361859a4.jpg)

## Expected behaviour

Colony should be created as normal

## Actual behaviour

The colony becomes inaccessible.
Moreover, the domain registered on the contract appears to be omit everything after and including the period.
`centrifuge.test` was created, but it shows up as `centrifuge` in the developer dashboard.
![image](https://user-images.githubusercontent.com/8453294/64184106-f7a84000-ce38-11e9-8b2d-58bcb61cc6ca.png)
`0x0a1a7E2F398d2C394411d2839F896B9D5fF7C6d7`

**Comment by rdig** [comment]
@chmanie and/or @area 

As I recall ENS domain aren't allowed to include `.` dots in they're name, right ?

So this is a case of the Wizard improperly validating the characters in the name.

**Comment by auryn-macmillan** [comment]
> As I recall ENS domain aren't allowed to include . dots in they're name, right ?

Not sure, their faq says:

> resolvers such as browsers and wallets should apply the nameprep algorithm to any names users enter before resolving; as a result, names that are not valid outputs of nameprep will not be resolvable by standard resolvers, making them effectively useless.

https://docs.ens.domains/frequently-asked-questions#what-about-foreign-characters-what-about-upper-case-letters-is-any-unicode-character-valid

**Comment by rdig** [comment]
I meant ours, since we're actually dealing with subdomains here, not the actual top level domains.

Also, as far as I recall, we have our own "registrar", and I'm not sure what it's character enforcing rules are.

**Comment by area** [comment]
> As I recall ENS domain aren't allowed to include . dots in they're name, right ?

Strictly, the answer to this question as presented is clearly 'yes', which is presumably how this has happened. `.`s separate subdomains. If the check being done is by putting through the normalise function in `eth-ens-namehash`, or similar, we are going to be told it is a valid ENS address. However, it is clearly not allowed to register the string `some.thing` as a subdomain of `whatever.eth`. I mean, you *can*, but any subsequent use of the domain by a correct ENS implementation will end up with a different hash, and therefore not be able to resolve the address.

> Also, as far as I recall, we have our own "registrar", and I'm not sure what it's character enforcing rules are.

I mean, yeah, but we have to play by the same rules as everyone else, otherwise our ENS names wouldn't work anywhere else!
