### ISSUE TITLE
Inbox notifications are starting to show signs of decreased performace

### ISSUE THREAD

**Issue by rdig** [JoinColony/colonyDapp#1843]
Loading the inbox, both popup and route, on my account _(a lot of subscriptions, hence notifications)_ is starting to load slowly.

Real-time demo:

![demo-inbox-long-loading-time](https://user-images.githubusercontent.com/1193222/65058157-72667480-d97c-11e9-8ab6-1cd6e9b386c7.gif)

To counteract this, we can add a pagination, or... we can get real fancy up in here and use the newly natively support Chrome lazy loading: https://developers.google.com/web/updates/2019/09/nic77#lazy-loading

**Comment by rdig** [comment]
> use the newly natively support Chrome lazy loading

@JoinColony/product you ok with that approach ?

**Comment by Karol-colony** [comment]
I am ok

**Comment by collinvine** [comment]
Sure

**Comment by rdig** [comment]
Very soon-ish this needs to get proper attention as the number of notifications will increase, and anything above 10 subscribed-to colonies presents a very long loading time

**Comment by rdig** [comment]
Just pasting some more issues to support the argument to look into optimizing this sooner rather then later:

When opening the notifications popover, the CPU usage spikes to 100%
![Screenshot from 2020-01-30 10-21-00](https://user-images.githubusercontent.com/1193222/73432065-984c4e80-434a-11ea-99af-5c10b1790b33.png)

The full page inbox, due to the number of notifications, is plagued by rendering issues and artifacts:
![Screenshot from 2020-01-30 10-20-09](https://user-images.githubusercontent.com/1193222/73432103-ad28e200-434a-11ea-9aef-7c4341c3fc0a.png)

**Comment by collinvine** [comment]
@rdig in the beta, we limited the items to 10 and had the CTA to see all inbox items in the full view.

Can we do that to help with the popover performance?
And then can we implement a solution on the full inbox view, such as lazy loading?

**Comment by rdig** [comment]
> Can we do that to help with the popover performance?

Yes but it's pointless _(see below)_

> And then can we implement a solution on the full inbox view, such as lazy loading?

The popover and the full view share the same code and the same data. Once implemented it will show up in both views

**Comment by collinvine** [comment]
Yes that makes sense, but we still may think about limiting the number of items in the popover for one or two reasons.

We could make an argument that says far number of users ever navigate to the full inbox page because historic notifications are not that important. What is important is the most recent notifications, of which 10 is enough.

That could then mean that we don't actually need to solve the performance issue because very few users have an issue with the performance of the inbox, and we could save some time right now.

We may also hypothesize that users may be more willing to accept longer loading times on the full inbox page than they are on the inbox pop over.

I'm trying to explore solutions that might be fast. maybe we can get away with just limiting the number of items in the popover for now without having to do anything with regards to loading performance.

Thoughts?

**Comment by rdig** [comment]
Yeah, I got the argument your going for in the first comment :slightly_smiling_face: 

But this only makes sense if I just limit the popover to 10... and that's it. That's the only work I do in the immediate future.

If I commit enough time to also make the full-screen inbox lazy load, then it doesn't make any sense to also cap the popover, as theoretically speaking I would be doing _more_ work as the code is the same for both _(theoretically, because the actual work to cap the popover is insignificant compared to the rest)_

**Comment by collinvine** [comment]
Right-eo. So ... you think we get 80% of the value by just limiting the popover to 10? 

That's my assumption. By limiting that, we get 80% of the results.
