### ISSUE TITLE
Token balance does not update when minime tokens are burned

### ISSUE THREAD

**Issue by auryn-macmillan** [JoinColony/colonyDapp#1942]
## Steps to reproduce

1. Create a [MiniMe token](https://medium.com/giveth/the-minime-token-open-sourced-by-giveth-2710c0210787) (probably with an Aragon DAO)
2. Send it to a colony
3. Burn the token that the colony received

## Expected behaviour

The token balance in the dapp should reflect the change after a token is burned.

## Actual behaviour

Token balance does not change when tokens minime tokens are burned.

![image](https://user-images.githubusercontent.com/8453294/70915603-1f867280-1fe8-11ea-8e42-15181223ed83.png)
![image](https://user-images.githubusercontent.com/8453294/70915661-3af17d80-1fe8-11ea-908a-57c0100f3032.png)
![image](https://user-images.githubusercontent.com/8453294/70915680-42188b80-1fe8-11ea-8c0c-e8c507baadb6.png)

**Comment by area** [comment]
The issue here is that, as well as being an ERC20 token that can be forked, MiniMe tokens include other functionality - including the ability for a (permissioned) third party to burn a token owned by someone, which is what is being used here. That burn transaction doesn't 'touch' the colony, so there is no way for the colony to know it has lost its tokens, and even if it did, if the tokens were distributed through multiple domains, we would have to come up with arbitrary rules to work out which tokens had been burned, and which domains, tasks etc should pay the price.

In the short term, there is no way to fix this, so I'm going to close the issue so devs coming through to pick up items aren't tempted by it. If it's any consolation, having a token snatched out from under them is something few contracts would deal with elegantly. If that's a problem, given that the underlying issue here is with the contracts, it should be moved to ColonyNetwork. _(And maybe throw another log on the fire of 'BYOT won't cause us problems')_

In the medium term, the most realistic solution is that, once arbitrary transactions are available to a colony, the colony will be able to fix this manually. But there's no way to guarantee they'd be able to 'keep up' with whoever was burning the tokens.

In the very long term, to solve this there is the suggestion that every pot could be its own contract, which is in theory possible but would increase gas costs for everything involving pots, and there is no clear upgrade path from where we are currently to there.
