### ISSUE TITLE
"Mint" button is missing from "Tokens" tab in the settings

### ISSUE THREAD

**Issue by auryn-macmillan** [JoinColony/colonyDapp#2247]
## Steps to reproduce

1. Head over to the tokens tab in the admin panel with an account that has root permission in a colony that created its own native token.

## Expected behaviour

You should be able to mint native tokens.

## Actual behaviour

The "mint" button is missing.
![image](https://user-images.githubusercontent.com/8453294/89654412-9aadd900-d896-11ea-89cb-8155a6e3dfb5.png)

**Comment by chmanie** [comment]
This is an apollo caching issue. From the discord:

> It's a caching issue. Because we are changing the signer apollo should reload some local resolvers but I don't know how to tell it
Also because of that we have to make sure that every function that we call that is dependent on permissions is reloaded
That's a whole lot of work
Because it's not super obvious in a lot of cases (like the mint tokens one)
Maybe we could clear the entire apollo cache on login
Force it to reload everything
