### ISSUE TITLE
Route users back to the Colony they joined after selecting a user name

### ISSUE THREAD

**Issue by willyogo** [JoinColony/colonyDapp#2599]
## Steps to reproduce

1. Connect a wallet to a new Colony
2. Click 'Join' in the top left
3. Claim a username

## Expected behaviour

* After username is claimed, user is returned to the Colony they just joined

## Actual behaviour

* After username is claimed, user sees options to 'Create a new Colony' or 'Join the Metacolony'

**Comment by rdig** [comment]
This is indeed a issue, whoever we have some plans on updating the _"Claim new username"_ flow which will remove the need for the additional route _(basically everything will be done is a single modal)_.

This will remove the `/create-user` _(and most likely the `/connect` route)_ which will inadvertently fix the issue you raised.

Due to the above, this will not be prioritized.
