### ISSUE TITLE
User receives "The MetaMask extension is not available." error message

### ISSUE THREAD

**Issue by chadwittman** [JoinColony/colonyDapp#2609]
## Steps to reproduce

1. Disconnect all wallets from Colony
2. Quit browser (full quit: CMD+Q)
3. Open https://xdai.colony.io/landing
4. Click Connect Wallet in Colony
5. Login to your Metamask
6. Connect wallet
7. You'll see: "The MetaMask extension is not available."
8. Hit "Try Again"

## Expected behaviour

* The user proceeds.

## Actual behaviour

* The user receives an error of "The MetaMask extension is not available."

## Why is this an issue? (optional)

* This is an issue because it is not clear how to remedy the solution. Closing out the tab and trying again also does not resolve this issue. A hard refresh is required.

## Suggestions (optional)

* Ideally, resolve the issue to prevent this error state from occurring.
* Minimally, update the copy to request the user to hard refresh their browser.

**Comment by rdig** [comment]
This is a side-effect of how metamask works.

That message means that metamask was not connected to the domain, and after connection to the domain (from the extension), it needs  page refresh so that we can connect to said wallet _(until then metamask blocks us)_

We can maybe come up with better copy that explains this, but other than that there's not much we can do.

**Comment by jakzilla** [comment]
I'm afraid I don't agree Raul, and this needs to be reopened. This is a problem peculiar to Colony. I do not experience it on any other dapps. I just tested with Idle.finance and uniswap.exchange and in both cases I turned up logged out of Metamask, logged in when prompted when I attempted to connect, and had no problem doing so.

It could be that these are refreshing automatically when the user logs into Metamask, but I think at least Uniswap is not reloading the page. Either way, we need to make this work in the same way those do (i.e. not with copy) because it's getting users stuck and unable to log in.

**Comment by chadwittman** [comment]
I'll try to keep track of the frequency of this issue, but it does seem to be fairly common. I'm at a n of 3 at the moment, but what I don't like about the issue is that it's a blocker to core functionality. I think with our core tech savvy users, trying a hard refresh is working — but I am guessing our less savvy users will start to bring this to the table.

I think we should scope the work required to copy Idle / Uniswap & leave it on our issues list (or migrate to a feature request).

**Comment by thycommodore** [comment]
fwiw this has come in via Canny too, it's now an n of 4.

**Comment by rdig** [comment]
Then I guess this gets bumped up the list in Maintenance :)
