### ISSUE TITLE
No confetti on purchase

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#2712]
## Steps to reproduce

1. Purchase a token within a token sale

## Expected behaviour

* An animated confetti overlay appears

<img width="1440" alt="EasterEgg@2x" src="https://user-images.githubusercontent.com/89165465/133132216-c805ad1f-c813-4d84-a12b-9987134fbb43.png">

## Actual behaviour

* No confetti

**Comment by rdig** [comment]
Yeah.... Are you sure you want that implemented...?

**Comment by rdig** [comment]
Converted into a feature request which we need to decide how we act upon.

**Comment by thycommodore** [comment]
@rdig can you give me a sense of the workload required on this task? My web2 brain thinks that this is as simple as grabbing a library that we like & slapping it in there, but I don't want to make an incorrect web3 assumption.

**Comment by rdig** [comment]
In terms of implementation it is a bit like you said, grabbing a library. In terms of wiring it up, a bit more tricky since we need to plug it the sale period timer update. Not trivial, but doable.

But I feel like you're missing my point. My point was always about the "feature" having no place in our Dapp. Hence why I asked you guys _(Product)_ numerous times to reconsider it.

**Comment by rdig** [comment]
As agreed with product, we're implementing the confetti feature for this. 

So whomever ends up taking this, please have a look at the previous implementation of this here: #2230

If I remember correctly, it was using the `react-confetti` library for this.
