### ISSUE TITLE
Autofocus back on chat after submitting (currently have to reselect the box)

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#2719]
### Story

As a user chatting in a coin machine sale, I want to be able to continue to type in the chat box after submitting so that I can stay engaged with the chat session.

### Description (optional, but useful!)

The workflow to send 2 chat messages works like this:

1. Click the input field
2. Type your message
3. Submit it
4. Click the input field
5. Type your message
6. Submit it

It feels like the common UX pattern is:

1. Click the input field
1. Type your message
1. Submit it
1. Type your message
1. Submit it

On step (3) the active focus remains on the text input field. 

### This issue is complete when...

- [ ] After submitting the chat entry, typing without clicking anything results in characters appearing in the input field

**Comment by rdig** [comment]
This is more of a global improvement rather than specific to Coin Machine, as this will also be applied to the comment box on the Actions and Motions pages.

Also, seeing as it won't take too much time to implement, I don't see a reason why we shouldn't tackle it.

I'm moving this out into Maintenance.
