### ISSUE TITLE
Coin Machine needs to be able to sell locked tokens.

### ISSUE THREAD

**Issue by jakzilla** [JoinColony/colonyDapp#2761]
Currently, Coin Machine can only sell unlocked tokens. This will be a problem for token sales, including ours, where it's important that tokens are not tradable while the token sale is in progress.

When Coin Machine is deployed/enabled, we also need to deploy a new authority for the token giving the coinmachine permissions to transfer the locked token.

**Comment by rdig** [comment]
I mean, this has to come from the contracts side no? So I guess this more in the ballpark of network / @area

**Comment by rdig** [comment]
After talking to Alex, this is actually in the realm of the dapp. We need to add a special case for the coin machine extension when installing. 

Instead of 1 transaction to install, as we have right now, we'll end up having 3 of them:
- install coin machine
- with the address of the deployed coin machine, deploy a new token authority
- point the existing token at the newly deployed token authority (via an arbitrary transaction)
