### ISSUE TITLE
Add Unlock Token Action Page

### ISSUE THREAD

**Issue by rdig** [JoinColony/colonyDapp#2817]
### * SEE BRIEF NEXT COMMENT DOWN

Outline:
- add action types
- add event to static map
- fetch correct data inside `colonyAction` resolver, from `getActionValues`
- pass down correct values to the message descriptor in the `DefaultAction` component
- add event to `ActionsPageFeed`

**Comment by arrenv** [comment]
## Specification

### Story

We want to be able to view a created Unlock Token Action, to provide more context on the action.


### Description

Most other actions already support the functionality by having a dedicated action page. This should save a lot of time as you should be able to plug into the existing `ActionsPage.tsx` component.

This update should involve the following:
* Add action types to `ColonyActions` and `ColonyAndExtensionsEvents` within `colonyActions.ts`.
* Assign values for action type, within `getValuesForActionType`.
* Update `staticMaps.ts` within the `ActionsPage` component to include the UnlockToken Action types, icon, events, and details.
* Fetch the correct data from `getActionValues`. You can refer to the event utils function `getVersionUpgradeActionValues` for reference on how you may be able to achieve this.
* Add correct action title and type to `en-actions.ts` in language folder.


### Design

This will utilise the existing action page design, so you shouldn't need to change or create any additional styles. You will need to confirm the following with product. Or, refer to what is being used in #2821, if it hasn't been started you will need to do this.

* Text used as motion title, refer to `actionsMessageDescriptors`
* Text used as motion type, refer to `actionsMessageDescriptors`
* Icon used as Action Type - There is a lock emoji icon (as of the screenshot below), already in img/icons folder that you should be able to use.

This is how it should look (example text and image only, needs to be confirmed):

![unlock-token-action-page](https://user-images.githubusercontent.com/33682027/147554736-449ba8c3-694e-48e6-a6ab-4a4f2e9c75a7.png)

## Implementation

### This issue is complete when...

- [ ] The Token Unlock Action has a dedicated action transaction page.
