### ISSUE TITLE
Update Unlock Token Modal to support creating a Motion

### ISSUE THREAD

**Issue by rdig** [JoinColony/colonyDapp#2818]
### * SEE BRIEF NEXT COMMENT DOWN

Outline:
- check for extension installed
- add forced switch
- reputation check and errors
- refactor transformer if needed
- logic to send different redux action (if motion)

**Comment by arrenv** [comment]
## Specification

### Story

We want to be able to create a motion for the Unlock Token action.


### Description

When unlocking a colony's native token, we want to be able to create a motion when the 'Motions & Disputes (Reputation)' extension is enabled and there is reputation in the colony.

You should be able to check how other actions are achieving this to get an idea on how to implement the same functionality in the Unlock Token modal.

This should involve the following:

- [ ] Perform a check to determine that the 'Motions & Disputes (Reputation)' extension is installed, refer to `TransferFundsDialogForm.tsx` for how this can be done.
- [ ] Add the  'Force' action switch to the modal, again you can refer to `TransferFundsDialogForm.tsx`
- [ ] Perform a check for reputation, and show errors if no reputation is present. Refer to the errors used in other actions, such as in `TransferFundsDialogForm.tsx`, using `NotEnoughReputation`.
- [ ] Add the logic to send different redux action (in case of a motion being created, such as `getFormAction` in `TransferFundsDialog.tsx`)


### Design

This will utilise the existing design and the same force switch as other action modals, so you shouldn't need to change or create any additional styles.

This is how it should look:

![unlock-token-motion-dialog](https://user-images.githubusercontent.com/33682027/147497085-1eadc536-38bb-42bd-8da2-5b61c898ff38.png)

Note: the copy used on the annotation description "Explain why you're unlocking the native token (optional)", this is an example on how it can be improved over the copy used in #2987. You will need to confirm the copy with product though.

## Implementation

### This issue is complete when...

The 'Motions & Disputes (Reputation)' extension is enabled, there is reputation in the colony, and:

- [ ] Checks 'Motions & Disputes (Reputation)' extension is installed
- [ ] The force switch is added
- [ ] Reputation check and errors functionality is includes
- [ ] The correct redux action is sent on submit (if motion)

**Comment by chinins** [comment]
@arrenv, I think that in your picture we are missing the `Create motion in Root` (disable select component) - similar to Mint tokens. Am I right or have we made a deliberate decision not to show it?
<img width="602" alt="Screenshot 2022-01-03 at 16 10 29" src="https://user-images.githubusercontent.com/34057551/147980732-82ea1742-0180-4f78-a447-a98021e82328.png">

**Comment by arrenv** [comment]
@chinins I deliberately didn't show it as the action can only be in root.

Although, I don't see there being any harm in having it in there for consistency. Maybe one for product?

**Comment by chinins** [comment]
> @chinins I deliberately didn't show it as the action can only be in root.
> 
> Although, I don't see there being any harm in having it in there for consistency. Maybe one for product?

That's why I gave mint tokens as an example. It can also be only in root (like a couple of others) and that's why it is disabled. If there was no deliberate decision from product or Raul to eliminate it then there is no need to contact product for this, we should add it as in other dialogs.

**Comment by arrenv** [comment]
@chinins ahh yes, good point. Thank you!
