### ISSUE TITLE
Only able to activate tokens if the amount begins with `1`

### ISSUE THREAD

**Issue by chinins** [JoinColony/colonyDapp#2888]
User who reported - `@willifox` from Shapeshift colony

**Comment by arrenv** [comment]
This issue has been explored by 3 separate team members on 3 different operating systems. So far, we have not been able to replicate it.

Due to various updates to the Dapp, it is possible that the issue has been resolved. I will reach out to the user on Shapeshift to see if it has been resolved on their end.

**Comment by arrenv** [comment]
I have received confirmation from `@willifox` that they are now no longer able to reproduce the issue.
