### ISSUE TITLE
Cannot interact with field to buy tokens during active coin machine sale

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#2915]
## Steps to reproduce

1. Go to an active sale ([ref 1](https://qaxdai.colony.io/colony/krausehouse111821/buy-tokens)) ([ref 2](https://qaxdai.colony.io/colony/krausehouse111721/buy-tokens))
2. Try to buy tokens

## Actual behaviour

* The field is unable to be interacted with.

![Screen Capture on 2021-11-18 at 10-23-27](https://user-images.githubusercontent.com/89165465/142444442-e046bee3-ff5f-4d86-9a1b-d2f3cb1dda08.gif)

**Comment by rdig** [comment]
I know what;s going on. It's a bad whitelist check. It's basically preventing you from buying because you're not whitelisted.

But here comes the bad check. It doesn't check if whitelist is actually enabled, it just checks if the current user is whitelisted or not.

This was introduced recently, but it's an easy fix.

_(if you install whitelist, and whitelist your user, it will work again -- this is just so you can continue to QA, until we push a deployment with this fix)_

**Comment by thycommodore** [comment]
@rdig I was hoping it was something of that nature, thanks for the work around — I'll keep hammering on QA 🙃
