### ISSUE TITLE
Price does not progress until the first purchase has been made.

### ISSUE THREAD

**Issue by jakzilla** [JoinColony/colonyDapp#2938]
Started a sale with a high starting price expecting to see the price begin to decrease after the first period had elapsed. Price did not progress as expected, and prices did not show up in the previous batches box until I made a purchase.

![Screenshot 2021-11-21 at 22 45 49](https://user-images.githubusercontent.com/4774274/142782016-417c015f-8656-46b7-9c05-0d609468afb1.png)

![Screenshot 2021-11-21 at 22 47 35](https://user-images.githubusercontent.com/4774274/142782019-ffec527b-9e98-4a2f-bc2b-ce8028a302c2.png)

After this purchase, the numbers in the price field of previous batches are incorrect.

![Screenshot 2021-11-21 at 22 53 18](https://user-images.githubusercontent.com/4774274/142782139-7e0e47e4-ff07-42ad-9906-5c1dd8ddbd46.png)

**Comment by area** [comment]
The prices being incorrect for periods were no sales were made is an issue with the frontend. I can go through it with Raul / on my own if he points me to the right place when we have time.

Price not evolving is due to the contracts. This behaviour is intended and is required to make the price-evolution-stops-when-empty work, but leads to this behaviour. Essentially, a transaction is required to start and stop price evolution. Stopping evolution is easy, it's when the contract runs out of tokens, and is automatically done when the sale that empties the coinmachine is made.

Starting evolution requires a transaction as well, and currently we piggyback on purchases made, which restarted the evolution as you can see here.

If we want to trigger price evolution without a purchase, there is a function we can call to do that, but there is currently not a mechanism in the frontend to call it. Note that this cannot be automatically done (on the contracts) when funds are transferred to the CoinMachine contract, as the `.transfer` does not touch the CoinMachine contract - it has no way of knowing, other than via another transaction, that it is no longer empty.

**Comment by rdig** [comment]
The problem with the price is a bit tricky. We calculate it backwards from the current period, basing it on data points where there we actual sales _(so we can get the "true" price from the contracts)_, then filling in the gaps.

It's hard to generate the "blanks" here without at least one data point from the contracts.

The only solution, if we can make it work that is, is to grab the current price somehow and inject it in datapoints, then base everything around it.

**Comment by kronosapiens** [comment]
Noting that one way to work around this is to load tokens to the contract _before_ initialisation. If tokens are present during initialisation, price evolution will begin regardless of whether purchase are made.
