### ISSUE TITLE
Update "Create new team" button to match spec

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#3117]
## Steps to reproduce

1. Navigate to the "All Teams" drop down.
2. Hover over the "Create new team" button.

## Expected behaviour

* Add the hover state to the "Create new team" button as of the spec.
* Also, ensure the plus icon is showing correctly and not being trimmed.

https://www.figma.com/file/DjVCPq7LpkjEMEfQZtKgBdC1/Style-Guide?node-id=94%3A0

![create-new-team-hover-state-new](https://user-images.githubusercontent.com/33682027/150358958-99d9bf65-792f-453c-b6a0-af22782bb616.png)

## Actual behaviour

* "Create new team" button currently has no hover state.

![hover-state-create-new-team](https://user-images.githubusercontent.com/33682027/150358905-1cba336c-1208-45ea-bc1e-8f54aeda8ab8.gif)

**Comment by linorallo** [comment]
Hi,

I'm trying to solve this but can't get the app running.
Followed the instructions:
(Selected node and npm versions)
1. npm install
2. npm run provision
3. npm run dev
 
This is the error that I'm getting:
`
> colony-dapp@4.4.3 dev
> scripts/start_all.js --foreground --skip-graph-node --skip-subgraph

Skipping graph-node
Skipping subgraph

Starting ganache...

Starting truffle...
Stack start failed.
spawn node_modules/.bin/truffle ENOENT
`

Any ideas on how to get it running?
Thanks

**Comment by rdig** [comment]
> Hi,
> 
> I'm trying to solve this but can't get the app running. Followed the instructions: (Selected node and npm versions)
> 
> 1. npm install
> 2. npm run provision
> 3. npm run dev
> 
> This is the error that I'm getting:
> 
> > colony-dapp@4.4.3 dev
> > scripts/start_all.js --foreground --skip-graph-node --skip-subgraph
> > Skipping graph-node
> > Skipping subgraph
> > Starting ganache...
> > Starting truffle...
> > Stack start failed.
> > spawn node_modules/.bin/truffle ENOENT
> 
> Any ideas on how to get it running? Thanks

For future, please ask debugging help in the #dev-dapp or #dev-general channels on discord.

For your specific case, it looks like the provision step didn't install the `colonyServer`'s submodule dependencies _(that's the one that  makes use of `truffle`)_ and most likely, because of that, it can't start the dev stack since the cli for `truffle` appears to be missing on your system

You can install the dependencies manually by going into src/lib/colonyNetwork and running `npm i` or `yarn`
