### ISSUE TITLE
Minting tokens motions don't update in the UI

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#3161]
## Steps to reproduce

1. Ensure you have the Motions & Disputes extension installed and you have reputation.
2. Create a motion to mint tokens.
3. Fully stake the motion so that it passes.
Note: you can speed up the motion period using the following in the console, which fast-forwards 3 days on chain: `curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"evm_increaseTime","params":[260000],"id": 1}' localhost:8545 && curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"evm_mine","params":[]}' localhost:8545`
4. Finalize the motion, and notice that the funds are not added to the colony.
5. Force another mint tokens action.
6. Notice that both the forced and the passed motion minting tokens are added to the colony.

## Expected behaviour

* A passed and finalized token minting motion should mint the tokens and show the newly minted token amount in the UI.

## Actual behaviour

* A passed and finalized token minting motion is not showing the newly minted tokens in the UI.
* Doing a forced token minting seems like the only way to get the motion minted tokens to appear.

![mint-token-motions](https://user-images.githubusercontent.com/33682027/152133312-9f100e78-9495-4a1f-aed3-c0098433e964.gif)

**Comment by ArmandoGraterol** [comment]
@arrenv

When you finalize the mint motion, we don't claim the tokens immediately through a transaction as we do for the mint action. That's why the UI "updates" itself when you make a mint action, in that action you are already sending a transaction to claim all of the claimable funds (That is the "Claim Pending Transactions" step that you on the gas station when you make a mint action), which would include the funds of the previous mint motion.

Try to pass a mint motion, then go to the event list, the funds should be claimable there.

Perhaps this is not a bug, and it could be more of a UX improvement? From your experience, it seems like it's not clear that you have to manually claim the minted tokens if they come from a motion

**Comment by arrenv** [comment]
Thank you @ArmandoGraterol, that is good to know. I agree, it is not a bug, but definitely seems like it could be UX improvement.  Do you recall the reasoning for having the Incoming funds on the events page and not on the 'Actions' page or anywhere else?

**Comment by ArmandoGraterol** [comment]
@arrenv Unfornutanely no, I think this was implemented by the time I started working in Colony. We may need to ask Product or Raul about it. Want me to do that or do you prefer to do it seeing that you are the one that created the issue?

**Comment by arrenv** [comment]
@ArmandoGraterol, good thinking, yeah go for it, since you are assigned to it :)

**Comment by arrenv** [comment]
Being resolved by new feature, Moving Claiming Funds.
