### ISSUE TITLE
IPFS and Reputation Miner status

### ISSUE THREAD

**Issue by dit7ya** [JoinColony/colonyDapp#3313]
The current server-status PR #3259 does not include IPFS and Reputation Miner being behind checks.

Those should be included.

It has to be considered how the reputation miner being behind should be checked.

Blocked by #3259.

**Comment by rdig** [comment]
For IPFS you can get away with only tracking the download gateway. Since currently we're using Cloudflare's endpoint, you can get away with just making a request to it and checking it's status.

For the Reputation Miner _(I think you mean Reputation Miner here, no?)_ ask @area as there might be some liveliness check that you can piggy-back onto

**Comment by rdig** [comment]
> Blocked by https://github.com/JoinColony/colonyDapp/pull/3259.

Are you sure? I think you can work on this as it is by using the #3259 branch as it's base, and just rebase your code on it.

Also, if you need people helping you out with this and taking on more issues, make sure to announce this in the Dev group.
