### ISSUE TITLE
Avatars border on hover changes

### ISSUE THREAD

**Issue by dit7ya** [JoinColony/colonyDapp#3428]
A. Currently the border color bleeds into the avatar if it is a transparent image.
B. Border on hover is not present for some avatars.

### Steps to reproduce

1. Go to https://xdai.colony.io/colony/shapeshift
2. Find an action with the avatar of the user hunt
3. Hover over their avatar

### Expected behaviour

Background color should not change.

### Actual behaviour

Border color bleeds into the background.
![2022-06-03_16-28](https://user-images.githubusercontent.com/14034137/171874584-e0242e82-64cd-40c3-a9de-baccbdd26d17.png)

### Steps to reproduce

1. Go to https://xdai.colony.io/colony/shapeshift/members
2. Hover over any avatar
3. No border appears

### Expected behaviour
Any user avatar that is clickable (and results into the popup) should have the borders.

**Comment by willm30** [comment]
@dit7ya With respect to part A, I don't notice the Avatar's background colour changing when I hover over hunt's avatar (although in my example the avatar image is different to yours). Perhaps because the background colour in your example was similar to the border colour they appeared to be bleeding into one another?

### No hover
![avatar-no-hover](https://user-images.githubusercontent.com/64402732/172386513-bc544d59-d2ba-49a6-9767-a20bd3e22f70.png)

### Hover
![avatar-border-hover](https://user-images.githubusercontent.com/64402732/172386527-fc85cfa3-5916-4d18-aef2-3eb03643391e.png)
