### ISSUE TITLE
With Address Book enabled, all SingleUserPicker fields should filter members

### ISSUE THREAD

**Issue by arrenv** [JoinColony/colonyDapp#3641]
## Steps to reproduce

1. Add a Member to the Address Book
2. Go to the Smite or Award modals
3. Try to select a member using the `SingleUserPicker`
4. The picker will show all members and not the filtered members as of the Address Book

This should apply to all `SingleUserPicker` fields, so this filter may work better at a higher level.

## Expected behaviour

* All `SingleUserPicker` fields should filter members when the Address Book is enabled

## Actual behaviour

* The `SingleUserPicker` is not filtering addresses in the Address Book

![user-picker-filter](https://user-images.githubusercontent.com/33682027/179314724-f8490666-b8d3-45a0-8b3f-8ebf3614f02b.gif)

**Comment by willm30** [comment]
@arrenv The filtering in the Payments user picker is using the WhiteListed addresses property in the "processedColony" resolver. Given that's being removed, is this issue now a wontfix?

**Comment by willm30** [comment]
> @arrenv The filtering in the Payments user picker is using the WhiteListed addresses property in the object returned by the "processedColony" resolver. Given that the WhiteList extn is being removed, and presumably that property also, is this issue now a wontfix?

Ok, I can see we'll still be keeping verifiedAddresses so I can use that

**Comment by willm30** [comment]
@arrenv I have a question re. the SingleUserPicker used by the BanUser dialog. I'm working on the assumption that if there is at least one member in the address book, all instances of the SingleUserPicker should display only the members in the address book. But applying this to the BanUser dialog, this would mean you can't ban non-verified members, because they wouldn't show up in the SingleUserPicker used in that dialog -- is that the idea? If it is, then should I also remove the option to ban the user on non-verified users? 

I have the same question with regard to the SingleUserPicker used in the PermissionManagement dialog. Is it the idea that if there's at least one member in the address book, you can no longer set permissions for non-verified members?

**Comment by arrenv** [comment]
@willm30 This is a good point. The main reason for wanting to implement this was (as a think about it now) a not well thought out way to allow Colonies with a lot of members to be able use the `SingleUserPicker`.

The `AddressBook` seems to really only make sense to be implemented for the payments recipient selection at the moment and possibly Awarding reputation. Anywhere else does not seem to really be needed.

So, possibly a better solution to the underlying issue would be to have a way for the `SingleUserPicker` to be able to handle lots of members.
